services:
  - type: web
    name: confession-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: confession-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: PAGE_SIZE
        value: 15
      - key: POINTS_PER_LIKE
        value: 1
      - key: POINTS_PER_DISLIKE
        value: -1

databases:
  - name: confession-db
    databaseName: confessions
    user: confession_user
    plan: free
